# Generated by Django 2.1.5 on 2019-04-01 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 6, 13, 35, 954777), verbose_name='date published'),
        ),
    ]
