# Generated by Django 2.1.5 on 2019-04-01 06:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190401_0613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 1, 6, 16, 31, 134481, tzinfo=utc), verbose_name='date published'),
        ),
    ]
